package VIEW;

import swing.JImageFrame;
import DAO.ConexaoBD;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 * Classe para criar o menu do sistema.
 * @author Jose
 */
public class MenuBiblioteca extends JImageFrame {

    TelaAlugueis alugueis;
    TelaUsuario usuario;
    TelaLivro livro;

    public MenuBiblioteca() {
        initComponents();
        init();
    } // Fim do método construtor

    private void init() {
        setIconImage(new ImageIcon(getClass().getResource("/images/icon.png")).getImage()); // definindo o ícone da janela/Frame
    } // Fim do método init

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menu = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();
        menuCadastro = new javax.swing.JMenu();
        menuLivros = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenuItem();
        menuAlugueis = new javax.swing.JMenu();
        menuRelatorio = new javax.swing.JMenu();
        menuLivrosPorAutor = new javax.swing.JMenuItem();
        menuAlugueisPorUsuario = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem2.setText("jMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Biblioteca");
        setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        setExtendedState(6);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        menu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menuArquivo.setText("Arquivo");

        menuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuSair);

        menu.add(menuArquivo);

        menuCadastro.setBackground(new java.awt.Color(255, 0, 51));
        menuCadastro.setText("Cadastro");

        menuLivros.setText("Livros");
        menuLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLivrosActionPerformed(evt);
            }
        });
        menuCadastro.add(menuLivros);

        menuUsuarios.setText("Usuários");
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosActionPerformed(evt);
            }
        });
        menuCadastro.add(menuUsuarios);

        menu.add(menuCadastro);

        menuAlugueis.setText("Aluguéis");
        menuAlugueis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuAlugueisMousePressed(evt);
            }
        });
        menu.add(menuAlugueis);

        menuRelatorio.setText("Relatório");

        menuLivrosPorAutor.setText("Livros por Autor");
        menuLivrosPorAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLivrosPorAutorActionPerformed(evt);
            }
        });
        menuRelatorio.add(menuLivrosPorAutor);

        menuAlugueisPorUsuario.setText("Aluguéis por Usuário");
        menuAlugueisPorUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlugueisPorUsuarioActionPerformed(evt);
            }
        });
        menuRelatorio.add(menuAlugueisPorUsuario);

        menu.add(menuRelatorio);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuAlugueisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAlugueisMousePressed
        if (alugueis != null) { // atributo alugueis não está nulo
            alugueis.dispose(); // Fecha a tela aluguéis
        }

        alugueis = new TelaAlugueis(); // nova instância da classe TelaAlugueis
        alugueis.setVisible(true); // mostra a tela aluguéis
    }//GEN-LAST:event_menuAlugueisMousePressed

    private void menuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosActionPerformed
        if (usuario == null) { // atributo usuario está nulo
            usuario = new TelaUsuario(); // nova instância da classe TelaUsuario
        }

        usuario.setVisible(true); // mostra a tela usuário
    }//GEN-LAST:event_menuUsuariosActionPerformed

    private void menuLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLivrosActionPerformed
        if (livro == null) { // atributo livro está nulo
            livro = new TelaLivro(); // nova instância da classe TelaLivro
        }

        livro.setVisible(true); // mostra a tela livro
    }//GEN-LAST:event_menuLivrosActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        // confirmando para fechar o programa
        if (JOptionPane.showConfirmDialog(null,
                "Deseja realmente sair?",
                "Sair",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0); // fecha o programa
        }
    }//GEN-LAST:event_menuSairActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // executar o método menuSairActionPerformed, pois também serve para confirmar a finalização do programa
        menuSairActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    private void menuLivrosPorAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLivrosPorAutorActionPerformed
	// gerar o relatório de livros por autor
        gerarRelatorio("src/RELATORIO/LivrosPorAutor.jasper", "Relatório de Livros por Autor");
    }//GEN-LAST:event_menuLivrosPorAutorActionPerformed

    private void menuAlugueisPorUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlugueisPorUsuarioActionPerformed
	// gerar o relatório de aluguéis por usuário
        gerarRelatorio("src/RELATORIO/AlugueisPorUsuario.jasper", "Relatório de Aluguéis por Usuário");
    }//GEN-LAST:event_menuAlugueisPorUsuarioActionPerformed

    // Método para gerar um relatório com o JasperReport
    private void gerarRelatorio(String sourceFileName, String title) {
        try {
            Connection con = new ConexaoBD().obterConexao();
            HashMap map = new HashMap<>(); // HashMap para passar como parâmetro para o JasperFillManager.fillReport, 
            // onde indica os valores dos parâmetros para gerar o relatório, definidos no JasperStudio, conforme os nomes dados será informado no nome da key do HashMap
            JasperReport jasperReport = (JasperReport)JRLoader.loadObjectFromFile(sourceFileName); // carregar o arquivo do relatório, indicado pelo seu caminho dentro do projeto
            // Ex.: "src/RELATORIO/AlugueisPorUsuario.jasper"
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, map, con); // aqui é preenchido o relatório com os dados do banco, informando o relatório, 
            // que é do tipo JasperReport, o Map (HashMap) com os parâmetros definido para gerar o relatório e a conexão (Connection) com o MySQL.
            JasperViewer jrviewer = new JasperViewer(jasperPrint, false); // variável jrviewer, do tipo JasperViewer, recebe uma nova instância da classe JasperViewer.
            jrviewer.setTitle(title); // define o título da janela do relatório
            jrviewer.setExtendedState(MAXIMIZED_BOTH); // definindo como tela cheia (janela expandida na horizontal e vertical)
            jrviewer.setVisible(true); // mostra o relatório, JasperViewer.
        } catch (JRException ex) { // erro ao gerar o relatório
            System.err.println("Error: " + ex.getMessage());
        }
    } // Fim do método gerarRelatorio

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the GraphiteLookAndFeel look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuBiblioteca().setVisible(true);
            }
        });
    } // Fim do método main

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuAlugueis;
    private javax.swing.JMenuItem menuAlugueisPorUsuario;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuLivros;
    private javax.swing.JMenuItem menuLivrosPorAutor;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuUsuarios;
    // End of variables declaration//GEN-END:variables

} // Fim da classe
